package Bitwise.No389_FindTheDifference;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.

 */
public class Solution {

    public char findTheDifference1(String s, String t) {
        char res = t.charAt(t.length() - 1);
        for(int i = 0; i < s.length();i ++){
            res ^= s.charAt(i);
            res ^= t.charAt(i);
        }
        return res;
    }
    public char findTheDifference(String s, String t) {
        char res = 0;
        for(char charS: s.toCharArray()) res ^= charS;
        for(char charT: t.toCharArray()) res ^= charT;
        return res;
    }
}
